### ISSUE TITLE
Make YAML front-matter as simple as possible

### ISSUE THREAD

**Issue by eonu** [bettermathematics/bettermathematics.github.io#48]
Many of the markdown files for the courses include a lot of information that I presume can just be retrieved from the `_data/courses.yml` file. For example:

```yaml
---
title: Introduction to Number Theory (MATH10071)
year: 3
semester: 2
course-acronym: int
archived: false
pinned: false
---
```

In this case, I believe `archived` and `pinned` default to false anyway, so it is not necessary to specify them, and also the `title`, `year` and `semester` fields are all specified in `_data/courses.yml`. It should be possible to make it so that you only need to specify the course acronym, and the rest of the variables necessary for the page can be retrieved from `_data/courses.yml`.

This would just eliminate a lot of unnecessary repetition.
